- name: Auto update last updated date
  run: |
    DATE=$(date +"%b. %d, %Y")

    sed -i "s|<span id=\"last-updated\"[^>]*>.*</span>|<span id=\"last-updated\" style=\"color:Red\">Last updated: ${DATE}</span>|" index.html

    git config --global user.name "github-actions[bot]"
    git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

    git add index.html
    git diff --cached --quiet || git commit -m "Auto update last updated date"
    git push
